import type { Metadata } from "next";
import { Geist, Geist_Mono, Jost } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";
import { CartProvider } from "@/context/CartContext";
import { ChatWidget } from "@/components/messaging/chat-widget";
import { GoogleMapsProvider } from "@/components/providers/google-maps-provider";
import { WelcomeModalWrapper } from "@/components/modals/welcome-modal-wrapper";

const jost = Jost({
  variable: "--font-jost",
  display: "swap",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SEWN",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  interactiveWidget: "resizes-content",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = await headers();
  const host = headersList.get("host") || "";
  const isAdminApp = host.startsWith("admin.");

  return (
    <html lang="en" data-theme="light">
      <body className={`${jost.className} antialiased overflow-x-hidden bg-white text-foreground`}>
        <GoogleMapsProvider>
          <CartProvider>
            {children}
            {!isAdminApp && <ChatWidget />}
            <WelcomeModalWrapper />
          </CartProvider>
        </GoogleMapsProvider>
      </body>
    </html>
  );
}